# See more config options https://github.com/foundry-rs/foundry/tree/master/config

[profile.default]
src = "src"
out = "out"
libs = ["lib"]

solc = "0.8.21"

remappings = [
    "@solady/=lib/solady/src",
    "@zeppelin/=lib/openzeppelin-contracts/contracts",
    "@upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts",
]
